name: chat_app_flutter
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.0-61.0.dev <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1
  firebase_core: ^1.16.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.17
  cloud_firestore: ^3.1.14
  firebase_storage: ^10.2.15
  google_sign_in: ^5.3.0
  lottie: ^1.3.0
  introduction_screen: ^3.0.2
  avatar_glow: ^2.0.2
  emoji_picker_flutter: ^1.1.2
  get_storage: ^2.0.3
  intl: ^0.17.0
  image_picker: ^0.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

  
  flutter_lints: ^2.0.0


  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/icon.png"

flutter:

  
  uses-material-design: true

  
  assets: 
    - assets/lottie/
    - assets/logo/

  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  